version: '3.7'
services:
    app:
        container_name: doctors-react
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports:
            - '8080:8080'
        environment:
            - NODE_ENV=development
    json-server:
        image: vimagick/json-server
        command: -H 0.0.0.0 -p 3000 -w .db/db.json --id upin
        ports:
            - '3030:3030'
        volumes:
            - ./data:/data
        restart: always
