export const UPDATE_DOCTORS = "UPDATE_DOCTORS";
export const UPDATE_SELECT_FILTER = "UPDATE_SELECT_FILTER";
export const UPDATE_TEXT_FILTER = "UPDATE_TEXT_FILTER";
export const UPDATE_DOCTOR_AVAILABILITY = "UPDATE_DOCTOR_AVAILABILITY";
